### ISSUE TITLE
Does not work with http urls. Requires https

### ISSUE THREAD

**Issue by tlaak** [Mozolli/MDT#1]
There's an error in (Chrome) console: `Mixed Content: The page at 'https://mozolli.github.io/MDT/' was loaded over HTTPS, but requested an insecure resource 'http://[site.url]'. This request has been blocked; the content must be served over HTTPS.`

**Comment by Mozolli** [comment]
Can't affect on what gets loaded over GitHub which is hosting the app. App works best when run locally and with local content. However, I've switched the default input to 'https'.
